### ISSUE TITLE
Write a complete guide on how to reproduce the experiment.

### ISSUE THREAD

**Issue by HayleyDeckers** [HayleyDeckers/Experiment-Design-2019-uu#1]
We should create a guide that can be used to reproduce the experiment. We should decide on which prerequisite knowledge we assume. For the writing part, I would suggest using [MdBook](https://rust-lang-nursery.github.io/mdBook/).

**Comment by HayleyDeckers** [comment]
This issue should probably be split into several sub-tasks once we start working on it.

**Comment by KiraMaathuis** [comment]
Finished: https://codingcat.nl/book/
