### ISSUE TITLE
Write a short report on the context and theory of the experiment.

### ISSUE THREAD

**Issue by HayleyDeckers** [HayleyDeckers/Experiment-Design-2019-uu#15]
Hard dead-line on 14-10-19. Probably most efficient to absorb this into issue #1 .

**Comment by KiraMaathuis** [comment]
Proposed layout/topics:

Interferometer design:
x discuss beamsplitters
x discuss path-length difference and how it causes interference
x discuss interference (and circular vs stripes patterns)

Measuring thermal expansion:
x using path-length difference to measure small expansion/shrinking
x important measures to make this possible (temp, number of wave-fronts)

MITE (Michaelson Interferometer Thermal Expansion)
