### ISSUE TITLE
Design and print a sample holder

### ISSUE THREAD

**Issue by HayleyDeckers** [HayleyDeckers/Experiment-Design-2019-uu#3]
We need to design and print a sample holder, that is, something to attach our heated element to such that we can measure it's thermal expansion.

**Comment by KiraMaathuis** [comment]
Design V0: 2 parts, 1 part printed well, 1 did not. Just started V1 print, Estimated to take 2 hours (done 17:20)

**Comment by HayleyDeckers** [comment]
Sample holder works. Slightly noisy, see #17, but the design seems fine.
