### ISSUE TITLE
Add thermocouple to the arduino.

### ISSUE THREAD

**Issue by HayleyDeckers** [HayleyDeckers/Experiment-Design-2019-uu#7]
Interface the arduino with the temperature measurement device.
Depends upon #6 and #3 .

**Comment by KiraMaathuis** [comment]
Soldered the AD590 temperature sensor to a set of jumper wires. White wire is V+,  black wire is V-. Added an AD590.md file with a link to the datasheet, an Arduino forum discussion on how to use it with Arduino and some sample code. 

Physical AD590 part and circuit is done, needs to be integrated into the Arduino code to work.

**Comment by HayleyDeckers** [comment]
Thermocouple works and can be read.
